### PR TITLE
[WIP] Suggesting corrections to translations

### PR DESCRIPTION
**Pull request by dingedi**
IN PROGRESS.

I started working on it, I open the PR now if you have any suggestions.
I'm not a very good designer, so maybe the design needs to be improved.

### CODE REVIEW

**Comment by PJ-Finlay** [comment]
Looks good to me!

This probably should be disabled by default and run if the server operator enables it with a command line flag. That way we're only prompting users to correct translations on servers that are likely to contribute the generated data.

image


image

**Comment by pierotofy** [comment]
Working on adding a flag to enable/disable suggestions! The UI looks great @dingedi

**Comment by pierotofy** [comment]
Added the swagger docs :+1: 

Good point about the privacy page; Google Translate does not have anything linked directly on their translation page when you submit contributions, although I'm sure they have a note somewhere buried in one of their policies.

**Comment by pierotofy** [comment]
Agreed.

**Pull request merged**
