### PR TITLE
Run test for pull requests, add some functional tests

### PR DESCRIPTION
**Pull request by dingedi**
This adds python tests for each PR, this will make it easier to prevent errors in the code.
I haven't yet found how to test the building of docker containers, I don't know too much about github action yet.

I also start to add functional test

### CODE REVIEW

**Comment by dingedi** [comment]
I removed python 3.6 because flask limiter 2.2 supports python >= 3.7

**Comment by dingedi** [comment]
I've added a few tests, I'll make more PR as I go along to add more tests, this will avoid introducing regressions unintentionally

**Comment by dingedi** [comment]
Is it good for python 3.6 support removal @pierotofy ? or we downgrade Flask-Limiter

**Comment by pierotofy** [comment]
I think it's OK to remove Python 3.6. :+1: 

Let me know once this is ready and I'll review. Thanks!

**Comment by dingedi** [comment]
this should be good now for python 3.6 :)

**Comment by dingedi** [comment]
@pierotofy I will add more tests later, there is already a small base.
I defined load-only for the tests to en, es to avoid that all the models are downloaded at each test (it was a lot since all this time!)

**Review by pierotofy — APPROVED** [review]
Looks great!

**Pull request merged**
