### PR TITLE
Christian

### PR DESCRIPTION
**Pull request by ecxod**
!!!! **ATTENTION** : Now this PR will change the design of the site, it will look like this one : [https://translate.zp1.net/](https://translate.zp1.net/)

I just prepared the "text" field for the learning and suggestions. that's why I relocated the api on a third button.

[more "dark" css](https://github.com/LibreTranslate/LibreTranslate/commit/19fdf825117a3f2e862db892950e0c2109253025) has nothing to do with it it is just to make the switch button "white" in a dark world

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey @ecxod :hand: thank you for the PR, but I'm not sure we want to hide / move the API code generation example; what's the goal here?

Perhaps we can toggle it on/off with a smaller button on the same tab as "Translate Text", but semantically it doesn't belong in the "Translate Text", "Translate Files" section.

**Comment by ecxod** [comment]
this https://github.com/LibreTranslate/LibreTranslate/pull/296/commits/b4f3a524222bf64e705355f9ef989b8eed4274d5 is just some css improvements for mobile

**Comment by ecxod** [comment]
> Hey @ecxod hand thank you for the PR, but I'm not sure we want to hide / move the API code generation example; what's the goal here?

I thought that there are 3 aspects. the "Text", the "Files", and the "api examples".

The users are simple people, who are not developers, who just want to translate something. These "hierogliefs" with brackets and square brackets just scare them to death :)) 
For us developers there is then the third button. We'll find it ;-)

> Perhaps we can toggle it on/off with a smaller button on the same tab as "Translate Text", but semantically it doesn't belong in the "Translate Text", "Translate Files" section.

I'll think about it for a week and get back to you later ;-)

**Comment by ecxod** [comment]
This is a comparation how it whould look on mobile

### ACTUAL VERSION 

 image image 
 
 And when you press the Hamburger  ...
 
image



- - - - - 
### NEW VERSION



 image image image

And with pressing the Hamburger ....

image

**Comment by ecxod** [comment]
this one just made all buttons the same width by making in main.css
```css
.btn-switch-type{
   width:12rem;
}
```

**Comment by ecxod** [comment]
image image image image

**Comment by pierotofy** [comment]
In desktop mode the text on the buttons seems to be a bit off:

image

(Chrome on Linux)

**Pull request closed without merging**
