### PR TITLE
build(docker): add arm version

### PR DESCRIPTION
**Pull request by euberdeveloper**
Add possibility to run LibreTranslate on docker with arm

Notes:
* the docker image is builded successfully, but was not checked during runtime
* the file was working only if moved to root

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey thanks @euberdeveloper ! I will merge this even though it hasn't been tested at runtime, hopefully it will allow others to test.

**Comment by euberdeveloper** [comment]
Will the image be pushed on the official dockerhub?

**Comment by pierotofy** [comment]
Once we get confirmation that it works, yes.

**Comment by euberdeveloper** [comment]
From my side, I confirm that it works

**Comment by pierotofy** [comment]
arm images are available: https://hub.docker.com/r/libretranslate/libretranslate/tags

**Comment by euberdeveloper** [comment]
Nice

Il lun 22 gen 2024, 18:50 Piero Toffanin ***@***.***> ha
scritto:

**Pull request merged**
