### PR TITLE
Make the github root less cluttered.

### PR DESCRIPTION
**Pull request by dingedi**
there have been quite a few miscellaneous scripts added to the root of the github and there are a lot of files, which makes it a bit more complicated to understand the project and which files are needed because some scripts are very specific.

- Migrate various scripts in a "scripts" folder
- Put the dockerfile in a .docker folder

### CODE REVIEW

**Comment by dingedi** [comment]
yes I will recheck, I wanted to see if the CI tests passed

**Comment by pierotofy** [comment]
Is this good to be reviewed/merged?

**Comment by dingedi** [comment]
> Is this good to be reviewed/merged?

Yes

**Comment by pierotofy** [comment]
Looks good! I've made some minor tweaks, but everything else worked great. Thanks @dingedi

**Pull request merged**
