### PR TITLE
Use lingua for language detection

### PR DESCRIPTION
**Pull request by pierotofy**
This PR replaces PyCLD2 with lingua (via linguars). It seems to work quite better for long texts (>20 characters), but struggles just like the others for shorter texts, as others have highlighted before.

It also comes with a severe runtime penalty, as it's a magnitude slower than PyCLD2. I'm not too inclined to merge this right away, at least until I have a solution to improving short texts as well.

### CODE REVIEW

**Comment by pierotofy** [comment]
Perhaps making a port of https://github.com/oprogramador/most-common-words-by-language and attempt to identify the words from here.

**Comment by pierotofy** [comment]
image

Fixes #508, #395, #247

Supersedes #396

**Comment by pierotofy** [comment]
Fixes #352

**Comment by pierotofy** [comment]
We now use a hybrid lingua + https://github.com/LibreTranslate/LexiLang for doing language detection.

Seems like a good improvement!

**Comment by rchost1** [comment]
Can you elaborate on this comment, please?

> We now use a hybrid lingua + https://github.com/LibreTranslate/LexiLang for doing language detection.

Does this imply that lingua-language-detection has been added to the main trunk of LT? Or you are using it in your own instance (as a trial)? (I'm not seeing it in my late version of the release.)

More to the point, can lingua be added to a future release of LT? Or is there a way one could upgrade ones' self-hosted container to add lingua?

Thanks!!

**Pull request merged**
