### PR TITLE
Improve Language detection

### LINKED ISSUE #247: French word not recognised
Hi,
I have used the translate.argosopentech.com API to translate french into english but got the same french sentence returned.

The sentence was: "Tout philosophe a deux philosophies : la sienne et celle de Spinoza."

As soon as I cut "la sienne et celle de spinoza" off the text, I get a successful french to english translation. This isn't the first I get this bug. Maybe due to a small french dataset on which libretranslate has been trained on...

### PR DESCRIPTION
**Pull request by Joshix-1**
Try to fix some of the issues raised in #395 and fix #247

- Replace CDL 2 with lingua-py for "a quick boost in accuracy"
- ingore languages that are not loaded for language detection

I didn't remove the old detection class, so maybe later multiple methods can be used.

With these changes `Tout philosophe a deux philosophies : la sienne et celle de Spinoza.` can be translated when is language is auto.
Even single german words like "Pfannkuchen" get recognised.

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey thanks @Joshix-1 !

It looks like this seems to struggle with single words; percentages are also incorrect.

image

If the intent is to remove cld2, let's just remove it; no need to keep it around. One can always browse git to find the previous code.

**Comment by Joshix-1** [comment]
I fixed the bug with the confidence percentage. 
> It looks like this seems to struggle with single words
Seems to be the case for some. For others it detects them more reliable. Language detections seems to be a difficult task

**Comment by Joshix-1** [comment]
know it doesn't detect the french :(

**Comment by Joshix-1** [comment]
lingua-py seemed to me the better and easier option.
- According to the graphs in the lingua-py README it is better than fasttext.
- on https://fasttext.cc there is no easy usage tutorial

I'm curious how lingua-py would perform with your test-data, so we could get an independent insight to whether it is better or worse than fasttext.

**Comment by Jourdelune** [comment]
With my experience, you must combine dictionary based language detection and different library with ngram.

I have made this library to detect discord message with a good accuracy:

https://github.com/Interaction-Bot/LanguageDetection

**Comment by Jourdelune** [comment]
Thank you for the advice! I didn't do metrics but I have used this paper to make the detector: https://aclanthology.org/W15-1703.pdf.

I have also my own dataset of discord message and I have reached an accuracy of 89% of good detection, and 4% of wrong detection if I use the reliability. I have do a medium post about that: https://medium.com/@jourdelune863/improving-language-detection-for-chat-discord-b148dfacc2e5.

I have trained a custom model of fastText on my type of message to have this reliability. But for you case I think just combine two detector can be enough.

**Comment by Jourdelune** [comment]
yes it's true but detection by dictionnary and add up the results of different detector to detect short text can help you if the accuracy is a problem :p

**Comment by pierotofy** [comment]
Closing in favor of #526 :pray:

**Pull request closed without merging**
