### PR TITLE
Fixed --load-only never found available_package

### PR DESCRIPTION
**Pull request by Sboti03**

### CODE REVIEW

**Comment by Sboti03** [comment]
I tested with hu and en and before that I got error`no available package`.
After this fix it only downloads English -> Hungarian, Hungarian -> English

**Comment by pierotofy** [comment]
Hey @Sboti03 :wave: thanks for the PR. I can't seem to be able to reproduce the issue you described?

```bash
docker run -p 5000:5000 -ti --rm libretranslate/libretranslate --load-only en,hu
Updating language models
Found 86 models
Keep 2 models
Downloading English → Hungarian (1.5) ...
Downloading Hungarian → English (1.5) ...
Loaded support for 2 languages (2 models total)!
Running on http://0.0.0.0:5000
```

Can you post the command you used?

**Comment by Sboti03** [comment]
```yml

version: "3.8"

services:
  libre-translate:
    container_name: wrap-libre-translate
    image: libretranslate/libretranslate
    networks:
      - docker-generated_net
    ports:
      - "5000:5000"
    tty: true
    environment:
      - LT_LOAD_ONLY=hu
      - LT_LOAD_ONLY=en
volumes:
  wrap-dbdata:
networks:
  docker-generated_net:
    external: true
```

**Comment by pierotofy** [comment]
`LT_LOAD_ONLY` should have a single entry and be set to `en,hu`.

**Pull request closed without merging**
