### PR TITLE
Add Helm Chart for LibreTranslate Deployment

### PR DESCRIPTION
**Pull request by drivard**
This PR introduces a comprehensive Helm chart for the deployment and management of LibreTranslate within a Kubernetes cluster. The chart provides a scalable and flexible solution to handle various deployment scenarios and requirements.

I use the k8s.yaml has the starting boiler plate.

## Key Features

- **Configurable Parameters:** Customize the deployment according to specific needs through `values.yaml`.
- **Persistent Storage Support:** Support for both ReadWriteOnce and ReadWriteMany access modes, allowing persistent storage for models and databases.
- **Authentication and Security:** Integration with basic authentication, security context, and image pull secrets.
- **Scalability:** Facilitates horizontal scaling with StatefulSets.
- **Health Checks:** Includes readiness and liveness probes for monitoring the health of the application.
- **Documentation:** Detailed README with instructions for installation, configuration, and upgrade.

## Usage Scenarios

- Deployment on Kubernetes cluster.
- Integration with existing storage solutions like NFS through storage class.
- Support for custom images and private registries.

## Testing

The chart has been tested on Kubernetes version 1.26.

- Tested the helm chart using RKE2 Kubernetes cluster on Harvester.
- Tested against the harvester/longhorn default storage class for ReadWriteOnce persistent volume.
- Tested against democratic-csi/nfs on TrueNAS Scale for ReadwriteMany persistent volume.
- Tested scaling of the Statefulset to 1 and 2 replicas with both ReadWriteMany and ReadWriteOnce storage class.

## Instructions

The README file includes detailed instructions for installation, customization, and upgrade.

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Thanks @drivard for this valuable contribution!

**Comment by PJ-Finlay** [comment]
Awesome thanks @drivard ! Should we add a doc to the main project Readme?

**Comment by drivard** [comment]
I thought about it let me propose a new pr about it i will look at it at beginning of next week

**Comment by drivard** [comment]
@PJ-Finlay @pierotofy giving it more thoughts. I am thinking you might want to consider creating a second repository for the chart in order to setup something like describe here in the [helm documentation](https://helm.sh/docs/howto/chart_releaser_action/).

I am not having the time now but I will in 2 weeks. I could give it a try if you are interested.

what do you think?

**Pull request merged**
