### PR TITLE
Require API key for submitting suggestions

### PR DESCRIPTION
**Pull request by fushinari**
Also removes limiter exemption

### CODE REVIEW

**Comment by pierotofy** [comment]
This would break the current client code, as https://github.com/LibreTranslate/LibreTranslate/blob/main/app/static/js/app.js#L288 does not forward the API key.

**Comment by fushinari** [comment]
Oops, sorry, will fix

**Comment by fushinari** [comment]
@pierotofy I'm sorry but I can't really test my changes unfortunately, because I get an error when trying to setup LibreTranslate locally:
```
ERROR: Could not find a version that satisfies the requirement ctranslate2==2.4.0 (from versions: 2.6.0)
ERROR: No matching distribution found for ctranslate2==2.4.0
```

**Comment by pierotofy** [comment]
No worries, looks good! Thanks. :pray:

**Pull request merged**
